// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zwwopmqkguibpscdubjv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp3d29wbXFrZ3VpYnBzY2R1Ymp2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxNzk4OTUsImV4cCI6MjA2NTc1NTg5NX0.XXx_BkgYAiZXiMX9nOYmIynf3V932iUR9GjY860N7fY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);